AWSTemplateFormatVersion: '2010-09-09'
Description: 'Popcorn App - DynamoDB Tables Setup'

Resources:
  PartyInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: popcorn-party-info
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: party_id
          AttributeType: S
      KeySchema:
        - AttributeName: party_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      Tags:
        - Key: Project
          Value: Popcorn

  UserSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: popcorn-user-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: party_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: party_id
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      Tags:
        - Key: Project
          Value: Popcorn

  UserPreferencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: popcorn-user-preferences
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: preference_id
          AttributeType: S
        - AttributeName: party_id
          AttributeType: S
      KeySchema:
        - AttributeName: preference_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PartyIndex
          KeySchema:
            - AttributeName: party_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      Tags:
        - Key: Project
          Value: Popcorn

  FinalVotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: popcorn-final-votes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: vote_id
          AttributeType: S
        - AttributeName: party_id
          AttributeType: S
      KeySchema:
        - AttributeName: vote_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PartyIndex
          KeySchema:
            - AttributeName: party_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      Tags:
        - Key: Project
          Value: Popcorn

  MoviesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: popcorn-movies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: movie_id
          AttributeType: S
      KeySchema:
        - AttributeName: movie_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      Tags:
        - Key: Project
          Value: Popcorn